title: Gallowz Humour
email: blog@gallowzhumour.dev
description: >-
    This is a blog, you goomba.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: Ragnyll
scm_icon: /assets/gitlab_icon.png

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

resume:
    name: Jake Gallow
    job_title: Software Engineer II
    email: jake.gallow@protonmail.com
    website: ragnyll.github.io
    avatar: assets/resume/hacker_smaller.png
